version: '2'
services:
  web:
    build: .
    ports:
     - "8080:8080"
    depends_on:
     - mongo
    networks:
     - internal
  mongo:
    image: mongo
    networks:
      internal:
        aliases:
          - mongo
networks:
  internal:
    driver: bridge
